### ISSUE TITLE
offer custom configuration location

### ISSUE THREAD

**Issue by job** [ecix/birdwatcher#5]
Its not that I don't like ecix, but I'd prefer not to have to stick your brand name in my `/etc` directory.

It would be great if I can point the tool with a command line option (`-f` perhaps?) to where I stored my configuration.

relevant: https://github.com/ecix/birdwatcher/blob/3e8140a4148012275c936b73d5291ef5323204b9/birdwatcher.go#L106-L110

**Comment by hellerve** [comment]
Hum, I thought we already fixed that (although we very obviously did not). I will take care of it. As for the multi-file option, I think it does make sense to have a local and a global config file.

Proposal for a behaviour of `-f/-file`: look for a file in `/etc`, then in `./etc`, then in `./etc`, adding the `.local` infix, where the latter supersedes the former (i.e. local overwrites global).

Does that make sense?

**Comment by job** [comment]
Sure! thanks

**Comment by hellerve** [comment]
This was addressed and fixed in #6.
